server:
  port: 10011

nacos:
  config:
    server-addr: 114.116.26.35:8848,114.116.140.153:8848,114.115.161.140:8848
    data-id: huawei_cloud
    group: DEFAULT_GROUP
    type: yaml
    max-retry: 10
    config-retry-time: 2333
    config-long-poll-timeout: 46000
    bootstrap.enable: true
    enable-remote-sync-config: true
    namespace: 7f1093be-cc98-4dac-abd0-fd101bbf6de8

#nacos.config.ext-config[0].data-id: huawei_cloud
#nacos.config.ext-config[0].group: DEFAULT_GROUP
#nacos.config.ext-config[0].max-retry: 10
#nacos.config.ext-config[0].type: yaml
#nacos.config.ext-config[0].config-retry-time: 2333
#nacos.config.ext-config[0].config-long-poll-timeout: 46000
#nacos.config.ext-config[0].enable-remote-sync-config: true
#nacos.config.ext-config[0].namespace: 7f1093be-cc98-4dac-abd0-fd101bbf6de8

spring:
  profiles.active: dev
# 数据库访问配置
# 主数据源，默认的
#spring.datasource.type: com.alibaba.druid.pool.DruidDataSource
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#spring.datasource.url: jdbc:mysql://localhost:3306/banban
#spring.datasource.username: root
#spring.datasource.password: 12345678

# 下面为连接池的补充设置，应用到上面所有数据源中
# 初始化大小，最小，最大
  datasource:
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  # 配置获取连接等待超时的时间
      max-wait: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      validation-query-timeout: 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      async-close-connection-enable: true
  # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
  # 配置下面参数用于启动监控页面，考虑安全问题，默认是关闭的，按需开启
      stat-view-servlet.enabled: true
      filter.stat.enabled: true
      web-stat-filter.enabled: true
      stat-view-servlet.login-username: admin
      stat-view-servlet.login-password: admin
